#' getSeasonFrate
#' splits up F rates generated by getF into seasonal, fleetwise vectors for use in SS3.
#' @param Fsim  vector returned from getF
#' @param nAnnualFrate  number of years for which to generate an annual F rate.
#' @export
getSeasonFrate<-function(Fsim=Fsim,nAnnualFrate=nyears){
  SeasonFrate <- NULL
  for (j in 1:nAnnualFrate)
  {
    SeasonFrate[(1+4*(j-1)):(4*j)]<- rep(Fsim[j]/4,4)     # equal rate among season
  }
  return(SeasonFrate)
}

## not run:
# scale1 =  0.1/1.323
# Fsim1 <- getFhist(nsim=1,Esd=0.001,nyears=nYears,dFmin=-0.07,dFmax=0.07,bb=-0.1,scale=scale1)
# meanF1 <-round(mean(apply(Fsim1,1,mean)),2)
# SeasonFrateF1 <- getSeasonFrate(Fsim1,nYears)
